### PR TITLE
Issue 14 - Integrity constraint violation: 1048 Column 'created' cannot be null

### LINKED ISSUE #14: Integrity constraint violation: 1048 Column 'created' cannot be null
I'm getting the following error:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created' cannot be null`

Steps to reproduce:

1. Spin up a new site
2. Enable "Sample Animal Content" module
3. Add and enable "Node Clone" module
4. Go to `/admin/config/content/clone` and change "Method to use when cloning a node" to "Save as a new node then edit."
5. Go to `/animals/saltwater-crocodile` and try to clone node
6. image
7. After confirmation, click "CLONE" and you should get this fatal error.

image

### PR DESCRIPTION
**Pull request by Sharif8190**
Fixes: #14

### CODE REVIEW

**Review by stpaultim — COMMENTED** [review]
I looked at this with @hosef today and he suggested that it may not be necessary to check "isset" here, because this is for a new node. Maybe we should just set the variable properly without the extra check.

Is it enough to simply put this?

$node->created = REQUEST_TIME;

**Comment by stpaultim** [comment]
@Sharif8190 Do you want to test the module with the simplier change?

**Comment by Sharif8190** [comment]
@stpaultim  Ok, I will test on my local, and then back to you.

**Comment by Sharif8190** [comment]
@stpaultim  I have tested $node->created = REQUEST_TIME; 
It is also working.

**Comment by robertgarrigos** [comment]
I agree with @stpaultim that it would need to be in the simpler form:

```
$node->created = REQUEST_TIME;
```
 as I explained [here.](https://github.com/backdrop-contrib/node_clone/issues/14#issuecomment-2408910682)
 
@Sharif8190, If you change this pr with this code, I will merge it. Thanks!

**Comment by robertgarrigos** [comment]
Sorry, just created a pr myself. closing this

**Pull request closed without merging**
